### ISSUE TITLE
How to stub out initializer?

### ISSUE THREAD

**Issue by woodall** [woodall/HashPageMe#1]
@tcopeland,

Running tests hits the [initializer](https://github.com/woodall/HashPageMe/blob/pair-w-tom-presenters/config/initializers/twitter.rb). 

I can't tell if this initializer needs to be refactored because it's hard to test?

Or, should I mock it out? :thought_balloon: 

```
[ pair-w-tom-presenters ] $ be bin/rake
Run options: --seed 50149

# Running:

.....E.

Finished in 0.474705s, 14.7460 runs/s, 25.2789 assertions/s.

  1) Error:
FetchersControllerTest#test_should_show_fetcher:
Twitter::Error::Unauthorized: Not authorized.
    config/initializers/twitter.rb:13:in `block in get_all_tweets'
    config/initializers/twitter.rb:10:in `get_all_tweets'
    app/controllers/fetchers_controller.rb:11:in `show'
    test/controllers/fetchers_controller_test.rb:28:in `block in <class:FetchersControllerTest>'

7 runs, 12 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by tcopeland** [comment]
@woodall yup, I'd do something like `Twitter::REST::Client.any_instance.expects(:get_all_tweets).returns([Twitter::Tweet.new(:id => 1, :body => "some viral tweet")]`.  

I'm not sure if those are the arguments that the `Twitter::Tweet` constructure requires, but you see what I mean?

**Comment by woodall** [comment]
I confess that _that_ line and it's role is currently the most confusing part of mocking.
So, I just added it [as is](https://github.com/woodall/HashPageMe/commit/e2583aeb97d091f4982217ab4a5591a67538fd0a#diff-015cb317f699db3b8e18403dd3dab024R32) to see if it would offer a different error, but no such luck.

```ruby 
  test "should show fetcher" do

    # _dw
    # I can't tell where this should go and how to use it...
    
    Twitter::REST::Client.any_instance.expects(:get_all_tweets).returns([Twitter::Tweet.new(:id => 1, :body => "some viral tweet")])
    get :show, id: @fetcher
    assert_response :success
  end
```

```
[ pair-w-tom-presenters ] $ be bin/rake
Run options: --seed 18975

# Running:

.....E.

Finished in 0.509809s, 13.7306 runs/s, 23.5382 assertions/s.

  1) Error:
FetchersControllerTest#test_should_show_fetcher:
Twitter::Error::Unauthorized: Not authorized.
    config/initializers/twitter.rb:13:in `block in get_all_tweets'
    config/initializers/twitter.rb:10:in `get_all_tweets'
    app/controllers/fetchers_controller.rb:11:in `show'
    test/controllers/fetchers_controller_test.rb:33:in `block in <class:FetchersControllerTest>'

7 runs, 12 assertions, 0 failures, 1 errors, 0 skips

[ 11:39 03/21 ] ~/Dropbox/300_code/learn/hashPage
[ pair-w-tom-presenters ] $
```

**Comment by tcopeland** [comment]
@woodall Cool, let's discuss further this afternoon, good stuff.

**Comment by woodall** [comment]
Believe it was [answered here](https://github.com/woodall/HashPageMe/pull/6)
